### ISSUE TITLE
Doesn’t work!

### ISSUE THREAD

**Issue by 4193883-eng** [PiSaucer/VanillaTweaksBedrock#2]
![image](https://user-images.githubusercontent.com/83756034/146731838-62640df9-9346-4488-b536-0bdc244f1492.png)
Minecraft bedrock IOS(1.18.2)

**Comment by PiSaucer** [comment]
That is Minecraft IOS issue, not the pack issue. It has been reported on the Minecraft Bug page: [MCPE-47250](https://bugs.mojang.com/browse/MCPE-47250). Try downloading the .zip version and unzip it into the folder.
