### ISSUE TITLE
XHR GET https://vanillatweaksbedrock.ml/mcpack/_master/readme.txt fails with HTTP 404 (not found)

### ISSUE THREAD

**Issue by nonperforming** [PiSaucer/VanillaTweaksBedrock#3]
"Error: Ajax error for /mcpack/_master/readme.txt : 404 Not Found"
This prevents users from downloading a zip or mcpack of selected tweaks.

**Comment by nonperforming** [comment]
Response...
```
404

File not found

The site configured at this address does not contain the requested file.

If this is your site, make sure that the filename case matches the URL.
For root URLs (like http://example.com/) you must provide an index.html file.

[Read the full documentation](https://help.github.com/pages/) for more information about using GitHub Pages.
[GitHub Status](https://githubstatus.com/) — [@githubstatus](https://twitter.com/githubstatus)
```

**Comment by PiSaucer** [comment]
I forgot that Jekyll blocks `_whatever` folders and files. [GitHub Pages](https://pages.github.com/) uses Jekyll so it was also blocked. So I renamed `_master` into `master` and edited all the references in the commit 12faafbdff822992f3255326a9e7cbabd1000e1e.Thank you for bringing this to my attention.
