### ISSUE TITLE
Load, update, and modify tweaks from an already-installed Resource Pack

### ISSUE THREAD

**Issue by nonperforming** [PiSaucer/VanillaTweaksBedrock#4]
Vanilla Tweaks (Java) has this in the form of a drag-and-drop a pack to upload or open the file manager to pick a folder.

Would it be possible to insert JSON or some kind of other text document in the MCPACK/ZIP that will stay when installed?

Uploaded is an example of Vanilla Tweaks (Java)'s implementation, done through a .txt file. If perhaps an extra file in the root of the MCPACK or zip does not get included while installed, would it be possible to encode a message in the pack's icon or description?

[Selected Packs.txt](https://github.com/PiSaucer/VanillaTweaksBedrock/files/8067277/Selected.Packs.txt)

**Comment by nonperforming** [comment]
Please label with [enhancement](https://github.com/PiSaucer/VanillaTweaksBedrock/labels/enhancement)

**Comment by PiSaucer** [comment]
I added the pack's names into the description and the `PACKS.txt` in 051ea169ece808a3577f6fd948e54c9f677723d4, over 15 days ago. I have yet to set it up to read packs and re-enable to options that were clicked. I am still focusing on adding the other packs  from the [`todo.md`](https://github.com/PiSaucer/VanillaTweaksBedrock/blob/main/todo.md).

**Comment by PiSaucer** [comment]
I made it so it can read the packs used in ca6915e7065c51f5d01999a437e2080b6100ac5e you can try it out at [vanillatweaksbedrock.ml/detect](https://vanillatweaksbedrock.ml/detect/). Still need to re-enable the options.

**Comment by PiSaucer** [comment]
Feature Implemented in 5645b93e240e8daec0d71dee36bdc1d108781310 or version [0.0.5](https://github.com/PiSaucer/VanillaTweaksBedrock/releases/tag/0.0.5). I have deleted the testing link since it no longer required. Thank you for the suggestion.

**Comment by nonperforming** [comment]
Thank you!
